--
-- PostgreSQL database dump
--

\restrict cEEah2NxwOSD6m7c9RzlgXWclbTEUcYOLTfd9aXiaq9R6QKMdC4dWMe7y1Eopie

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-08-24 13:28:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16391)
-- Name: antecedente_familiar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.antecedente_familiar (
    ant_fam_id integer NOT NULL,
    paciente_id integer,
    consulta_id integer,
    parentesco character varying(50),
    patologia character varying(150),
    descripcion text
);


ALTER TABLE public.antecedente_familiar OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: antecedente_familiar_ant_fam_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.antecedente_familiar ALTER COLUMN ant_fam_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.antecedente_familiar_ant_fam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16398)
-- Name: auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria (
    auditoria_id integer CONSTRAINT permiso_permiso_id_not_null NOT NULL,
    descripcion character varying(200),
    modulo character varying(50),
    id_usuario integer,
    fecha_hora timestamp(0) without time zone DEFAULT now(),
    accion text
);


ALTER TABLE public.auditoria OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16405)
-- Name: cita; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cita (
    cita_id integer NOT NULL,
    nombres_paciente character varying(40),
    apellidos_paciente character varying(40),
    nombres_representante character varying(40),
    apellidos_representante character varying(40),
    numero_hc integer,
    fecha_hora timestamp without time zone,
    consulta_id integer
);


ALTER TABLE public.cita OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16409)
-- Name: cita_cita_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cita ALTER COLUMN cita_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cita_cita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16410)
-- Name: consulta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consulta (
    consulta_id integer NOT NULL,
    paciente_id integer,
    medico_id integer,
    tipo_id integer,
    enfermedad_id integer,
    fecha_hora timestamp without time zone DEFAULT now(),
    peso double precision,
    talla double precision,
    sc double precision,
    fc double precision,
    fr double precision,
    subjetivo text,
    plan_trabajo text,
    proxima_cita date,
    status integer
);


ALTER TABLE public.consulta OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16417)
-- Name: consulta_consulta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consulta ALTER COLUMN consulta_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consulta_consulta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16418)
-- Name: enfermedad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enfermedad (
    enfermedad_id integer NOT NULL,
    tipo boolean,
    descripcion character varying(255)
);


ALTER TABLE public.enfermedad OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16422)
-- Name: enfermedad_enfermedad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enfermedad ALTER COLUMN enfermedad_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enfermedad_enfermedad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16423)
-- Name: estado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado (
    estado_id integer NOT NULL,
    nombre character varying(25) NOT NULL
);


ALTER TABLE public.estado OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16428)
-- Name: estado_estado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estado ALTER COLUMN estado_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estado_estado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16429)
-- Name: examen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.examen (
    examen_id integer NOT NULL,
    nombre character varying(100),
    unidad_medida character varying(20),
    valor_ref_min double precision,
    valor_ref_max double precision,
    status character varying(15) DEFAULT 'Activo'::character varying
);


ALTER TABLE public.examen OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16434)
-- Name: examen_examen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.examen ALTER COLUMN examen_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.examen_examen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16435)
-- Name: frotis_fsp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.frotis_fsp (
    fsp_id integer NOT NULL,
    consulta_id integer,
    seg_val double precision,
    lin_val double precision,
    mon_val double precision,
    eos_val double precision,
    blastos_val double precision,
    morfologia text,
    observaciones text
);


ALTER TABLE public.frotis_fsp OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16441)
-- Name: frotis_fsp_fsp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.frotis_fsp ALTER COLUMN fsp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.frotis_fsp_fsp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16442)
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16448)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO postgres;

--
-- TOC entry 5245 (class 0 OID 0)
-- Dependencies: 235
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- TOC entry 236 (class 1259 OID 16449)
-- Name: municipio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.municipio (
    municipio_id integer NOT NULL,
    estado_id integer,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.municipio OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16454)
-- Name: municipio_municipio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.municipio ALTER COLUMN municipio_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.municipio_municipio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16455)
-- Name: orden_laboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orden_laboratorio (
    orden_id integer NOT NULL,
    consulta_id integer,
    tipo_seguimiento character varying(100),
    fecha_solicitud timestamp without time zone DEFAULT now(),
    status character varying(20) DEFAULT 'Pendiente'::character varying
);


ALTER TABLE public.orden_laboratorio OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16461)
-- Name: orden_laboratorio_orden_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orden_laboratorio ALTER COLUMN orden_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_laboratorio_orden_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16462)
-- Name: paciente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paciente (
    paciente_id integer NOT NULL,
    persona_id integer,
    hc character varying(30),
    status integer
);


ALTER TABLE public.paciente OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16466)
-- Name: paciente_paciente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.paciente ALTER COLUMN paciente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paciente_paciente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16467)
-- Name: paciente_representante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paciente_representante (
    paciente_id integer NOT NULL,
    representante_id integer NOT NULL,
    parentesco character varying(50),
    es_principal boolean DEFAULT true
);


ALTER TABLE public.paciente_representante OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16473)
-- Name: parroquia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parroquia (
    parroquia_id integer NOT NULL,
    municipio_id integer,
    nombre character varying(40) NOT NULL
);


ALTER TABLE public.parroquia OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16478)
-- Name: parroquia_parroquia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parroquia ALTER COLUMN parroquia_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parroquia_parroquia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16479)
-- Name: permiso_permiso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auditoria ALTER COLUMN auditoria_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.permiso_permiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16480)
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    persona_id integer NOT NULL,
    nombres character varying(100),
    apellidos character varying(100),
    fecha_nacimiento date,
    sexo character varying(12),
    cedula character varying(15),
    telefono character varying(20),
    email character varying(100),
    estado_id integer,
    municipio_id integer,
    parroquia_id integer,
    direccion_exacta text
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16486)
-- Name: persona_persona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persona ALTER COLUMN persona_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 16487)
-- Name: protocolo_ciclo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.protocolo_ciclo (
    ciclo_id integer NOT NULL,
    protocolo_id integer,
    numero_ciclo integer,
    fecha_inicio date,
    estado character varying(20) DEFAULT 'Pendiente'::character varying
);


ALTER TABLE public.protocolo_ciclo OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 16492)
-- Name: protocolo_ciclo_ciclo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.protocolo_ciclo ALTER COLUMN ciclo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.protocolo_ciclo_ciclo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 16493)
-- Name: protocolo_sesion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.protocolo_sesion (
    sesion_id integer NOT NULL,
    ciclo_id integer,
    fecha_hora timestamp without time zone,
    tipo_sesion character varying(50),
    status character varying(20) DEFAULT 'Programada'::character varying
);


ALTER TABLE public.protocolo_sesion OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 16498)
-- Name: protocolo_sesion_sesion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.protocolo_sesion ALTER COLUMN sesion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.protocolo_sesion_sesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 16499)
-- Name: protocolo_tratamiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.protocolo_tratamiento (
    protocolo_id integer NOT NULL,
    paciente_id integer,
    consulta_id integer,
    nombre character varying(100),
    indicaciones text,
    fecha_inicio date,
    estado character varying(20) DEFAULT 'Activo'::character varying,
    usuario_medico_id integer
);


ALTER TABLE public.protocolo_tratamiento OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 16506)
-- Name: protocolo_tratamiento_protocolo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.protocolo_tratamiento ALTER COLUMN protocolo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.protocolo_tratamiento_protocolo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 16507)
-- Name: representante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.representante (
    representante_id integer NOT NULL,
    persona_id integer,
    ocupacion character varying(100)
);


ALTER TABLE public.representante OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 16511)
-- Name: representante_representante_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.representante ALTER COLUMN representante_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.representante_representante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 16512)
-- Name: resultado_laboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resultado_laboratorio (
    resultado_id integer NOT NULL,
    orden_id integer,
    examen_id integer,
    valor_encontrado double precision,
    status character varying(20) DEFAULT 'Activo'::character varying
);


ALTER TABLE public.resultado_laboratorio OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 16517)
-- Name: resultado_laboratorio_resultado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resultado_laboratorio ALTER COLUMN resultado_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resultado_laboratorio_resultado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 16518)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    rol_id integer NOT NULL,
    nombre character varying(50)
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 16522)
-- Name: rol_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN rol_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 16523)
-- Name: tipaje_sanguineo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipaje_sanguineo (
    tipaje_id integer NOT NULL,
    paciente_id integer,
    fecha date,
    grupo_ab character varying(3),
    factor_rh character varying(3),
    fenotipo_extendido text,
    genetica_transfusional text,
    metodo character varying(50),
    usuario_registrador_id integer,
    status character varying(20) DEFAULT 'Activo'::character varying
);


ALTER TABLE public.tipaje_sanguineo OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 16530)
-- Name: tipaje_sanguineo_tipaje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipaje_sanguineo ALTER COLUMN tipaje_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipaje_sanguineo_tipaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 16531)
-- Name: tipo_consulta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_consulta (
    tipo_id integer NOT NULL,
    nombre character varying(50)
);


ALTER TABLE public.tipo_consulta OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 16535)
-- Name: tipo_consulta_tipo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_consulta ALTER COLUMN tipo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_consulta_tipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 16536)
-- Name: transfusion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transfusion (
    transfusion_id integer NOT NULL,
    paciente_id integer,
    unidad_id integer,
    consulta_id integer,
    fecha_hora timestamp without time zone,
    volumen_adm double precision,
    status character varying(20) DEFAULT 'Realizada'::character varying
);


ALTER TABLE public.transfusion OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 16541)
-- Name: transfusion_transfusion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transfusion ALTER COLUMN transfusion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfusion_transfusion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 16542)
-- Name: unidad_hemocomponente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unidad_hemocomponente (
    unidad_id integer NOT NULL,
    codigo_bolsa character varying(20),
    tipo_componente character varying(100),
    grupo_rh character varying(5),
    volumen_ml double precision,
    fecha_vencimiento date,
    status character varying(20) DEFAULT 'Disponible'::character varying
);


ALTER TABLE public.unidad_hemocomponente OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 16547)
-- Name: unidad_hemocomponente_unidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.unidad_hemocomponente ALTER COLUMN unidad_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidad_hemocomponente_unidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 16548)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    usuario_id integer NOT NULL,
    persona_id integer,
    username character varying(50),
    password_hash character varying(255),
    status integer,
    id_rol integer
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 16552)
-- Name: usuario_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN usuario_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4983 (class 2604 OID 16553)
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- TOC entry 4995 (class 2606 OID 16555)
-- Name: antecedente_familiar antecedente_familiar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.antecedente_familiar
    ADD CONSTRAINT antecedente_familiar_pkey PRIMARY KEY (ant_fam_id);


--
-- TOC entry 4999 (class 2606 OID 16557)
-- Name: cita cita_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_pkey PRIMARY KEY (cita_id);


--
-- TOC entry 5001 (class 2606 OID 16559)
-- Name: consulta consulta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consulta
    ADD CONSTRAINT consulta_pkey PRIMARY KEY (consulta_id);


--
-- TOC entry 5003 (class 2606 OID 16561)
-- Name: enfermedad enfermedad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enfermedad
    ADD CONSTRAINT enfermedad_pkey PRIMARY KEY (enfermedad_id);


--
-- TOC entry 5005 (class 2606 OID 16563)
-- Name: estado estado_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_nombre_key UNIQUE (nombre);


--
-- TOC entry 5007 (class 2606 OID 16565)
-- Name: estado estado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_pkey PRIMARY KEY (estado_id);


--
-- TOC entry 5009 (class 2606 OID 16567)
-- Name: examen examen_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.examen
    ADD CONSTRAINT examen_nombre_key UNIQUE (nombre);


--
-- TOC entry 5011 (class 2606 OID 16569)
-- Name: examen examen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.examen
    ADD CONSTRAINT examen_pkey PRIMARY KEY (examen_id);


--
-- TOC entry 5013 (class 2606 OID 16571)
-- Name: frotis_fsp frotis_fsp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.frotis_fsp
    ADD CONSTRAINT frotis_fsp_pkey PRIMARY KEY (fsp_id);


--
-- TOC entry 5015 (class 2606 OID 16573)
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5017 (class 2606 OID 16575)
-- Name: municipio municipio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_pkey PRIMARY KEY (municipio_id);


--
-- TOC entry 5019 (class 2606 OID 16577)
-- Name: orden_laboratorio orden_laboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden_laboratorio
    ADD CONSTRAINT orden_laboratorio_pkey PRIMARY KEY (orden_id);


--
-- TOC entry 5021 (class 2606 OID 16579)
-- Name: paciente paciente_hc_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_hc_key UNIQUE (hc);


--
-- TOC entry 5023 (class 2606 OID 16581)
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (paciente_id);


--
-- TOC entry 5025 (class 2606 OID 16583)
-- Name: paciente_representante paciente_representante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente_representante
    ADD CONSTRAINT paciente_representante_pkey PRIMARY KEY (paciente_id, representante_id);


--
-- TOC entry 5027 (class 2606 OID 16585)
-- Name: parroquia parroquia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parroquia
    ADD CONSTRAINT parroquia_pkey PRIMARY KEY (parroquia_id);


--
-- TOC entry 4997 (class 2606 OID 16587)
-- Name: auditoria permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT permiso_pkey PRIMARY KEY (auditoria_id);


--
-- TOC entry 5029 (class 2606 OID 16589)
-- Name: persona persona_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_cedula_key UNIQUE (cedula);


--
-- TOC entry 5031 (class 2606 OID 16591)
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (persona_id);


--
-- TOC entry 5033 (class 2606 OID 16593)
-- Name: protocolo_ciclo protocolo_ciclo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_ciclo
    ADD CONSTRAINT protocolo_ciclo_pkey PRIMARY KEY (ciclo_id);


--
-- TOC entry 5035 (class 2606 OID 16595)
-- Name: protocolo_sesion protocolo_sesion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_sesion
    ADD CONSTRAINT protocolo_sesion_pkey PRIMARY KEY (sesion_id);


--
-- TOC entry 5037 (class 2606 OID 16597)
-- Name: protocolo_tratamiento protocolo_tratamiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_tratamiento
    ADD CONSTRAINT protocolo_tratamiento_pkey PRIMARY KEY (protocolo_id);


--
-- TOC entry 5039 (class 2606 OID 16599)
-- Name: representante representante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.representante
    ADD CONSTRAINT representante_pkey PRIMARY KEY (representante_id);


--
-- TOC entry 5041 (class 2606 OID 16601)
-- Name: resultado_laboratorio resultado_laboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resultado_laboratorio
    ADD CONSTRAINT resultado_laboratorio_pkey PRIMARY KEY (resultado_id);


--
-- TOC entry 5043 (class 2606 OID 16603)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (rol_id);


--
-- TOC entry 5045 (class 2606 OID 16605)
-- Name: tipaje_sanguineo tipaje_sanguineo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipaje_sanguineo
    ADD CONSTRAINT tipaje_sanguineo_pkey PRIMARY KEY (tipaje_id);


--
-- TOC entry 5047 (class 2606 OID 16607)
-- Name: tipo_consulta tipo_consulta_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_consulta
    ADD CONSTRAINT tipo_consulta_nombre_key UNIQUE (nombre);


--
-- TOC entry 5049 (class 2606 OID 16609)
-- Name: tipo_consulta tipo_consulta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_consulta
    ADD CONSTRAINT tipo_consulta_pkey PRIMARY KEY (tipo_id);


--
-- TOC entry 5051 (class 2606 OID 16611)
-- Name: transfusion transfusion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfusion
    ADD CONSTRAINT transfusion_pkey PRIMARY KEY (transfusion_id);


--
-- TOC entry 5053 (class 2606 OID 16613)
-- Name: unidad_hemocomponente unidad_hemocomponente_codigo_bolsa_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidad_hemocomponente
    ADD CONSTRAINT unidad_hemocomponente_codigo_bolsa_key UNIQUE (codigo_bolsa);


--
-- TOC entry 5055 (class 2606 OID 16615)
-- Name: unidad_hemocomponente unidad_hemocomponente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidad_hemocomponente
    ADD CONSTRAINT unidad_hemocomponente_pkey PRIMARY KEY (unidad_id);


--
-- TOC entry 5057 (class 2606 OID 16617)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (usuario_id);


--
-- TOC entry 5059 (class 2606 OID 16619)
-- Name: usuario usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_username_key UNIQUE (username);


--
-- TOC entry 5060 (class 2606 OID 16620)
-- Name: antecedente_familiar antecedente_familiar_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.antecedente_familiar
    ADD CONSTRAINT antecedente_familiar_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5061 (class 2606 OID 16625)
-- Name: antecedente_familiar antecedente_familiar_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.antecedente_familiar
    ADD CONSTRAINT antecedente_familiar_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5063 (class 2606 OID 16630)
-- Name: cita cita_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5064 (class 2606 OID 16635)
-- Name: consulta consulta_enfermedad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consulta
    ADD CONSTRAINT consulta_enfermedad_id_fkey FOREIGN KEY (enfermedad_id) REFERENCES public.enfermedad(enfermedad_id) DEFERRABLE;


--
-- TOC entry 5065 (class 2606 OID 16640)
-- Name: consulta consulta_medico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consulta
    ADD CONSTRAINT consulta_medico_id_fkey FOREIGN KEY (medico_id) REFERENCES public.usuario(usuario_id) DEFERRABLE;


--
-- TOC entry 5066 (class 2606 OID 16645)
-- Name: consulta consulta_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consulta
    ADD CONSTRAINT consulta_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5067 (class 2606 OID 16650)
-- Name: consulta consulta_tipo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consulta
    ADD CONSTRAINT consulta_tipo_id_fkey FOREIGN KEY (tipo_id) REFERENCES public.tipo_consulta(tipo_id) DEFERRABLE;


--
-- TOC entry 5068 (class 2606 OID 16655)
-- Name: frotis_fsp frotis_fsp_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.frotis_fsp
    ADD CONSTRAINT frotis_fsp_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5069 (class 2606 OID 16660)
-- Name: municipio municipio_estado_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_estado_id_fkey FOREIGN KEY (estado_id) REFERENCES public.estado(estado_id) DEFERRABLE;


--
-- TOC entry 5070 (class 2606 OID 16665)
-- Name: orden_laboratorio orden_laboratorio_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden_laboratorio
    ADD CONSTRAINT orden_laboratorio_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5071 (class 2606 OID 16670)
-- Name: paciente paciente_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id) DEFERRABLE;


--
-- TOC entry 5072 (class 2606 OID 16675)
-- Name: paciente_representante paciente_representante_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente_representante
    ADD CONSTRAINT paciente_representante_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5073 (class 2606 OID 16680)
-- Name: paciente_representante paciente_representante_representante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente_representante
    ADD CONSTRAINT paciente_representante_representante_id_fkey FOREIGN KEY (representante_id) REFERENCES public.representante(representante_id) DEFERRABLE;


--
-- TOC entry 5074 (class 2606 OID 16685)
-- Name: parroquia parroquia_municipio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parroquia
    ADD CONSTRAINT parroquia_municipio_id_fkey FOREIGN KEY (municipio_id) REFERENCES public.municipio(municipio_id) DEFERRABLE;


--
-- TOC entry 5075 (class 2606 OID 16690)
-- Name: persona persona_estado_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_estado_id_fkey FOREIGN KEY (estado_id) REFERENCES public.estado(estado_id) DEFERRABLE;


--
-- TOC entry 5076 (class 2606 OID 16695)
-- Name: persona persona_municipio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_municipio_id_fkey FOREIGN KEY (municipio_id) REFERENCES public.municipio(municipio_id) DEFERRABLE;


--
-- TOC entry 5077 (class 2606 OID 16700)
-- Name: persona persona_parroquia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_parroquia_id_fkey FOREIGN KEY (parroquia_id) REFERENCES public.parroquia(parroquia_id) DEFERRABLE;


--
-- TOC entry 5078 (class 2606 OID 16705)
-- Name: protocolo_ciclo protocolo_ciclo_protocolo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_ciclo
    ADD CONSTRAINT protocolo_ciclo_protocolo_id_fkey FOREIGN KEY (protocolo_id) REFERENCES public.protocolo_tratamiento(protocolo_id) DEFERRABLE;


--
-- TOC entry 5079 (class 2606 OID 16710)
-- Name: protocolo_sesion protocolo_sesion_ciclo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_sesion
    ADD CONSTRAINT protocolo_sesion_ciclo_id_fkey FOREIGN KEY (ciclo_id) REFERENCES public.protocolo_ciclo(ciclo_id) DEFERRABLE;


--
-- TOC entry 5080 (class 2606 OID 16715)
-- Name: protocolo_tratamiento protocolo_tratamiento_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_tratamiento
    ADD CONSTRAINT protocolo_tratamiento_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5081 (class 2606 OID 16720)
-- Name: protocolo_tratamiento protocolo_tratamiento_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_tratamiento
    ADD CONSTRAINT protocolo_tratamiento_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5082 (class 2606 OID 16725)
-- Name: protocolo_tratamiento protocolo_tratamiento_usuario_medico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.protocolo_tratamiento
    ADD CONSTRAINT protocolo_tratamiento_usuario_medico_id_fkey FOREIGN KEY (usuario_medico_id) REFERENCES public.usuario(usuario_id) DEFERRABLE;


--
-- TOC entry 5083 (class 2606 OID 16730)
-- Name: representante representante_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.representante
    ADD CONSTRAINT representante_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id) DEFERRABLE;


--
-- TOC entry 5084 (class 2606 OID 16735)
-- Name: resultado_laboratorio resultado_laboratorio_examen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resultado_laboratorio
    ADD CONSTRAINT resultado_laboratorio_examen_id_fkey FOREIGN KEY (examen_id) REFERENCES public.examen(examen_id) DEFERRABLE;


--
-- TOC entry 5085 (class 2606 OID 16740)
-- Name: resultado_laboratorio resultado_laboratorio_orden_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resultado_laboratorio
    ADD CONSTRAINT resultado_laboratorio_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES public.orden_laboratorio(orden_id) DEFERRABLE;


--
-- TOC entry 5086 (class 2606 OID 16745)
-- Name: tipaje_sanguineo tipaje_sanguineo_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipaje_sanguineo
    ADD CONSTRAINT tipaje_sanguineo_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5087 (class 2606 OID 16750)
-- Name: tipaje_sanguineo tipaje_sanguineo_usuario_registrador_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipaje_sanguineo
    ADD CONSTRAINT tipaje_sanguineo_usuario_registrador_id_fkey FOREIGN KEY (usuario_registrador_id) REFERENCES public.usuario(usuario_id) DEFERRABLE;


--
-- TOC entry 5088 (class 2606 OID 16755)
-- Name: transfusion transfusion_consulta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfusion
    ADD CONSTRAINT transfusion_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consulta(consulta_id) DEFERRABLE;


--
-- TOC entry 5089 (class 2606 OID 16760)
-- Name: transfusion transfusion_paciente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfusion
    ADD CONSTRAINT transfusion_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.paciente(paciente_id) DEFERRABLE;


--
-- TOC entry 5090 (class 2606 OID 16765)
-- Name: transfusion transfusion_unidad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfusion
    ADD CONSTRAINT transfusion_unidad_id_fkey FOREIGN KEY (unidad_id) REFERENCES public.unidad_hemocomponente(unidad_id) DEFERRABLE;


--
-- TOC entry 5062 (class 2606 OID 16770)
-- Name: auditoria usuario a permiso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT "usuario a permiso" FOREIGN KEY (id_usuario) REFERENCES public.usuario(usuario_id) NOT VALID;


--
-- TOC entry 5091 (class 2606 OID 16775)
-- Name: usuario usuario a rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "usuario a rol" FOREIGN KEY (id_rol) REFERENCES public.rol(rol_id) NOT VALID;


--
-- TOC entry 5092 (class 2606 OID 16780)
-- Name: usuario usuario_persona_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id) DEFERRABLE;


-- Completed on 2026-08-24 13:28:57

--
-- PostgreSQL database dump complete
--

\unrestrict cEEah2NxwOSD6m7c9RzlgXWclbTEUcYOLTfd9aXiaq9R6QKMdC4dWMe7y1Eopie

