CREATE TABLE "estado" (
  "estado_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "municipio" (
  "municipio_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado_id" int,
  "nombre" varchar(50) NOT NULL
);

CREATE TABLE "parroquia" (
  "parroquia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "municipio_id" int,
  "nombre" varchar(40) NOT NULL
);

CREATE TABLE "cie10" (
  "enfermedad_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(10) UNIQUE,
  "descripcion" varchar(255)
);

CREATE TABLE "examen_catalogo" (
  "examen_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE,
  "unidad_medida" varchar(20),
  "valor_ref_min" float,
  "valor_ref_max" float,
  "status" varchar(15) DEFAULT 'Activo'
);

CREATE TABLE "tipo_consulta_catalogo" (
  "tipo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE
);

CREATE TABLE "permiso" (
  "permiso_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(100) UNIQUE,
  "descripcion" varchar(200),
  "modulo" varchar(50)
);

CREATE TABLE "rol" (
  "rol_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "rol_permiso" (
  "rol_id" int,
  "permiso_id" int,
  PRIMARY KEY ("rol_id", "permiso_id")
);

CREATE TABLE "persona" (
  "persona_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar(100),
  "apellidos" varchar(100),
  "fecha_nacimiento" date,
  "sexo" varchar(12),
  "cedula" varchar(15) UNIQUE,
  "telefono" varchar(20),
  "email" varchar(100),
  "estado_id" int,
  "municipio_id" int,
  "parroquia_id" int,
  "direccion_exacta" text,
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "representante" (
  "representante_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" int,
  "ocupacion" varchar(100)
);

CREATE TABLE "paciente" (
  "paciente_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" int,
  "hc" varchar(30) UNIQUE,
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "paciente_representante" (
  "paciente_id" int,
  "representante_id" int,
  "parentesco" varchar(50),
  "es_principal" boolean DEFAULT true,
  PRIMARY KEY ("paciente_id", "representante_id")
);

CREATE TABLE "usuario" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" int,
  "username" varchar(50) UNIQUE,
  "password_hash" varchar(255),
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "usuario_permiso" (
  "usuario_id" int,
  "permiso_id" int,
  PRIMARY KEY ("usuario_id", "permiso_id")
);

CREATE TABLE "tipaje_sanguineo" (
  "tipaje_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" int,
  "fecha" date,
  "grupo_ab" varchar(3),
  "factor_rh" varchar(3),
  "fenotipo_extendido" text,
  "genetica_transfusional" text,
  "metodo" varchar(50),
  "usuario_registrador_id" int,
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "consulta" (
  "consulta_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" int,
  "usuario_medico_id" int,
  "tipo_id" int,
  "cie10_id" int,
  "fecha_hora" datetime DEFAULT (now()),
  "motivo_consulta" text,
  "peso" float,
  "talla" float,
  "sc" float,
  "fc" int,
  "fr" int,
  "subjetivo" text,
  "plan_trabajo" text,
  "proxima_cita" date,
  "status" varchar(20) DEFAULT 'Abierta'
);

CREATE TABLE "frotis_fsp" (
  "fsp_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consulta_id" int,
  "seg_val" float,
  "lin_val" float,
  "mon_val" float,
  "eos_val" float,
  "blastos_val" float,
  "morfologia" text,
  "observaciones" text
);

CREATE TABLE "protocolo_tratamiento" (
  "protocolo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" int,
  "consulta_id" int,
  "nombre" varchar(100),
  "indicaciones" text,
  "fecha_inicio" date,
  "estado" varchar(20) DEFAULT 'Activo',
  "usuario_medico_id" int
);

CREATE TABLE "protocolo_ciclo" (
  "ciclo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "protocolo_id" int,
  "numero_ciclo" int,
  "fecha_inicio" date,
  "estado" varchar(20) DEFAULT 'Pendiente'
);

CREATE TABLE "protocolo_sesion" (
  "sesion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ciclo_id" int,
  "fecha_hora" datetime,
  "tipo_sesion" varchar(50),
  "status" varchar(20) DEFAULT 'Programada'
);

CREATE TABLE "antecedente_familiar" (
  "ant_fam_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" int,
  "consulta_id" int,
  "parentesco" varchar(50),
  "patologia" varchar(150),
  "descripcion" text
);

CREATE TABLE "orden_laboratorio" (
  "orden_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consulta_id" int,
  "tipo_seguimiento" varchar(100),
  "fecha_solicitud" datetime DEFAULT (now()),
  "status" varchar(20) DEFAULT 'Pendiente'
);

CREATE TABLE "resultado_laboratorio" (
  "resultado_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_id" int,
  "examen_id" int,
  "valor_encontrado" float,
  "status" varchar(20) DEFAULT 'Activo'
);

CREATE TABLE "unidad_hemocomponente" (
  "unidad_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_bolsa" varchar(20) UNIQUE,
  "tipo_componente" varchar(100),
  "grupo_rh" varchar(5),
  "volumen_ml" float,
  "fecha_vencimiento" date,
  "status" varchar(20) DEFAULT 'Disponible'
);

CREATE TABLE "transfusion" (
  "transfusion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" int,
  "unidad_id" int,
  "consulta_id" int,
  "fecha_hora" datetime,
  "volumen_adm" float,
  "status" varchar(20) DEFAULT 'Realizada'
);

CREATE TABLE "auditoria" (
  "auditoria_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "accion" varchar(100),
  "entidad" varchar(50),
  "entidad_id" int,
  "valor_anterior" text,
  "valor_nuevo" text,
  "fecha_hora" datetime DEFAULT (now())
);

ALTER TABLE "municipio" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("estado_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parroquia" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipio" ("municipio_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("rol_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("permiso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("estado_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipio" ("municipio_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("parroquia_id") REFERENCES "parroquia" ("parroquia_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "representante" ADD FOREIGN KEY ("persona_id") REFERENCES "persona" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paciente" ADD FOREIGN KEY ("persona_id") REFERENCES "persona" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paciente_representante" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "paciente_representante" ADD FOREIGN KEY ("representante_id") REFERENCES "representante" ("representante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("persona_id") REFERENCES "persona" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_permiso" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("permiso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tipaje_sanguineo" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tipaje_sanguineo" ADD FOREIGN KEY ("usuario_registrador_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("usuario_medico_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("tipo_id") REFERENCES "tipo_consulta_catalogo" ("tipo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("cie10_id") REFERENCES "cie10" ("enfermedad_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "frotis_fsp" ADD FOREIGN KEY ("consulta_id") REFERENCES "consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "protocolo_tratamiento" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "protocolo_tratamiento" ADD FOREIGN KEY ("consulta_id") REFERENCES "consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "protocolo_tratamiento" ADD FOREIGN KEY ("usuario_medico_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "protocolo_ciclo" ADD FOREIGN KEY ("protocolo_id") REFERENCES "protocolo_tratamiento" ("protocolo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "protocolo_sesion" ADD FOREIGN KEY ("ciclo_id") REFERENCES "protocolo_ciclo" ("ciclo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "antecedente_familiar" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "antecedente_familiar" ADD FOREIGN KEY ("consulta_id") REFERENCES "consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_laboratorio" ADD FOREIGN KEY ("consulta_id") REFERENCES "consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resultado_laboratorio" ADD FOREIGN KEY ("orden_id") REFERENCES "orden_laboratorio" ("orden_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resultado_laboratorio" ADD FOREIGN KEY ("examen_id") REFERENCES "examen_catalogo" ("examen_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfusion" ADD FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfusion" ADD FOREIGN KEY ("unidad_id") REFERENCES "unidad_hemocomponente" ("unidad_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfusion" ADD FOREIGN KEY ("consulta_id") REFERENCES "consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditoria" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;
