CREATE SCHEMA "usuarios";

CREATE SCHEMA "logistica";

CREATE SCHEMA "desechable";

CREATE TABLE "usuarios"."usuario" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer,
  "username" varchar(50) UNIQUE,
  "password_hash" varchar(255),
  "status" integer,
  "id_rol" integer
);

CREATE TABLE "usuarios"."rol" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50)
);

CREATE TABLE "usuarios"."auditoria" (
  "auditoria_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(200),
  "modulo" varchar(50),
  "id_usuario" integer,
  "fecha_hora" timestamp(0) DEFAULT (now()),
  "accion" text
);

CREATE TABLE "logistica"."cita" (
  "cita_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres_paciente" varchar(60),
  "apellidos_paciente" varchar(60),
  "nombres_representante" varchar(60),
  "apellidos_representante" varchar(60),
  "numero_hc" integer,
  "fecha_hora" timestamp,
  "consulta_id" integer
);

CREATE TABLE "logistica"."paciente" (
  "paciente_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer,
  "hc" integer UNIQUE,
  "status" integer
);

CREATE TABLE "logistica"."consulta" (
  "consulta_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer,
  "medico_id" integer,
  "tipo" integer,
  "enfermedad_id" integer,
  "fecha_hora" timestamp DEFAULT (now()),
  "peso" text,
  "talla" text,
  "sc" text,
  "fc" text,
  "fr" text,
  "subjetivo" text,
  "plan_trabajo" text,
  "proxima_cita" date,
  "status" integer
);

CREATE TABLE "logistica"."enfermedad" (
  "enfermedad_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" integer,
  "descripcion" varchar(255)
);

CREATE TABLE "logistica"."medicina" (
  "medicina_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(255)
);

CREATE TABLE "logistica"."medicina_pro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_protocolo" integer NOT NULL,
  "id_medicina" integer NOT NULL,
  "via_admin" integer NOT NULL,
  "id_fase" integer NOT NULL
);

CREATE TABLE "logistica"."fase" (
  "fase_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" integer NOT NULL
);

CREATE TABLE "logistica"."protocolo" (
  "protocolo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" text NOT NULL
);

CREATE TABLE "estado" (
  "estado_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "municipio" (
  "municipio_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL
);

CREATE TABLE "parroquia" (
  "parroquia_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) NOT NULL
);

CREATE TABLE "persona" (
  "persona_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar(100),
  "apellidos" varchar(100),
  "fecha_nacimiento" date,
  "sexo" varchar(12),
  "cedula" varchar(10) UNIQUE,
  "telefono" varchar(20),
  "email" varchar(100),
  "estado_id" integer,
  "municipio_id" integer,
  "parroquia_id" integer,
  "direccion_exacta" text
);

CREATE TABLE "desechable"."antecedente_familiar" (
  "ant_fam_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer,
  "consulta_id" integer,
  "parentesco" varchar(50),
  "patologia" varchar(255),
  "descripcion" text
);

CREATE TABLE "desechable"."examen" (
  "examen_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE,
  "unidad_medida" varchar(20),
  "valor_ref_min" text,
  "valor_ref_max" text,
  "status" varchar(15) DEFAULT ('Activo')
);

CREATE TABLE "desechable"."frotis_fsp" (
  "fsp_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consulta_id" integer,
  "seg_val" text,
  "lin_val" text,
  "mon_val" text,
  "eos_val" text,
  "blastos_val" text,
  "morfologia" text,
  "observaciones" text
);

CREATE TABLE "desechable"."representante" (
  "representante_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" integer,
  "ocupacion" varchar(100)
);

CREATE TABLE "desechable"."resultado_laboratorio" (
  "resultado_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_id" integer,
  "examen_id" integer,
  "valor_encontrado" text,
  "status" varchar(20) DEFAULT ('Activo')
);

CREATE TABLE "desechable"."tipaje_sanguineo" (
  "tipaje_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer,
  "fecha" date,
  "grupo_ab" varchar(3),
  "factor_rh" varchar(3),
  "fenotipo_extendido" text,
  "genetica_transfusional" text,
  "metodo" varchar(50),
  "usuario_registrador_id" integer,
  "status" varchar(20) DEFAULT ('Activo')
);

CREATE TABLE "desechable"."transfusion" (
  "transfusion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer,
  "unidad_id" integer,
  "consulta_id" integer,
  "fecha_hora" timestamp,
  "volumen_adm" text,
  "status" varchar(20) DEFAULT ('Realizada')
);

CREATE TABLE "desechable"."unidad_hemocomponente" (
  "unidad_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_bolsa" varchar(20) UNIQUE,
  "tipo_componente" varchar(100),
  "grupo_rh" varchar(5),
  "volumen_ml" text,
  "fecha_vencimiento" date,
  "status" varchar(20) DEFAULT ('Disponible')
);

CREATE TABLE "desechable"."orden_laboratorio" (
  "orden_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consulta_id" integer,
  "tipo_seguimiento" varchar(100),
  "fecha_solicitud" timestamp DEFAULT (now()),
  "status" varchar(20) DEFAULT ('Pendiente')
);

CREATE TABLE "desechable"."paciente_representante" (
  "paciente_id" integer NOT NULL,
  "representante_id" integer NOT NULL,
  "parentesco" varchar(50),
  "es_principal" boolean DEFAULT true,
  PRIMARY KEY ("paciente_id", "representante_id")
);

CREATE TABLE "logistica"."sala" (
  "sala_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(80) UNIQUE NOT NULL,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "logistica"."protocolo_tratamiento" (
  "protocolo_tratamiento_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer NOT NULL,
  "consulta_id" integer NOT NULL,
  "protocolo_id" integer NOT NULL,
  "usuario_medico_id" integer NOT NULL,
  "fecha_inicio" date NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'Activo',
  "indicaciones" text
);

CREATE TABLE "logistica"."protocolo_ciclo" (
  "ciclo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "protocolo_tratamiento_id" integer NOT NULL,
  "numero_ciclo" integer NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" varchar(20) NOT NULL DEFAULT 'Pendiente',
  CONSTRAINT "protocolo_ciclo_tratamiento_numero_unique" UNIQUE ("protocolo_tratamiento_id", "numero_ciclo")
);

CREATE TABLE "logistica"."protocolo_sesion" (
  "sesion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ciclo_id" integer NOT NULL,
  "medicina_pro_id" integer NOT NULL,
  "sala_id" integer NOT NULL,
  "fecha_hora" timestamp NOT NULL,
  "tipo_sesion" varchar(50) NOT NULL,
  "dosis" varchar(100) NOT NULL,
  "via_administracion" varchar(100) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Programada',
  "fecha_hora_aplicacion" timestamp,
  "usuario_enfermero_id" integer,
  "identidad_confirmada" boolean NOT NULL DEFAULT false,
  "observaciones_enfermeria" text
);

CREATE INDEX "protocolo_sesion_agenda_index"
  ON "logistica"."protocolo_sesion" ("fecha_hora", "sala_id", "status");

CREATE TABLE "logistica"."observacion_enfermeria" (
  "observacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sala_id" integer,
  "paciente_id" integer,
  "sesion_id" integer,
  "usuario_id" integer NOT NULL,
  "categoria" varchar(20) NOT NULL,
  "gravedad" varchar(20) NOT NULL,
  "fecha_hora" timestamp NOT NULL,
  "descripcion" text NOT NULL,
  "accion_tomada" text
);

CREATE INDEX "observacion_enfermeria_fecha_categoria_index"
  ON "logistica"."observacion_enfermeria" ("fecha_hora", "categoria");

CREATE TABLE "logistica"."reaccion_adversa" (
  "reaccion_adversa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente_id" integer NOT NULL,
  "sesion_id" integer,
  "transfusion_id" integer,
  "usuario_id" integer NOT NULL,
  "categoria" varchar(30) NOT NULL,
  "gravedad" varchar(20) NOT NULL,
  "fecha_hora" timestamp NOT NULL,
  "descripcion" text NOT NULL,
  "intervencion" text,
  CONSTRAINT "reaccion_adversa_origen_check"
    CHECK (("sesion_id" IS NOT NULL AND "transfusion_id" IS NULL) OR ("sesion_id" IS NULL AND "transfusion_id" IS NOT NULL))
);

CREATE INDEX "reaccion_adversa_paciente_fecha_index"
  ON "logistica"."reaccion_adversa" ("paciente_id", "fecha_hora");

ALTER TABLE "desechable"."transfusion"
  ADD COLUMN "fecha_hora_aplicacion" timestamp,
  ADD COLUMN "sala_id" integer,
  ADD COLUMN "enfermera_id" integer,
  ADD COLUMN "identidad_confirmada" boolean NOT NULL DEFAULT false;

ALTER TABLE "desechable"."transfusion"
  ADD FOREIGN KEY ("sala_id") REFERENCES "logistica"."sala" ("sala_id"),
  ADD FOREIGN KEY ("enfermera_id") REFERENCES "usuarios"."usuario" ("usuario_id");

ALTER TABLE "logistica"."protocolo_tratamiento"
  ADD FOREIGN KEY ("paciente_id") REFERENCES "logistica"."paciente" ("paciente_id"),
  ADD FOREIGN KEY ("consulta_id") REFERENCES "logistica"."consulta" ("consulta_id"),
  ADD FOREIGN KEY ("protocolo_id") REFERENCES "logistica"."protocolo" ("protocolo_id"),
  ADD FOREIGN KEY ("usuario_medico_id") REFERENCES "usuarios"."usuario" ("usuario_id");

ALTER TABLE "logistica"."protocolo_ciclo"
  ADD FOREIGN KEY ("protocolo_tratamiento_id") REFERENCES "logistica"."protocolo_tratamiento" ("protocolo_tratamiento_id");

ALTER TABLE "logistica"."protocolo_sesion"
  ADD FOREIGN KEY ("ciclo_id") REFERENCES "logistica"."protocolo_ciclo" ("ciclo_id"),
  ADD FOREIGN KEY ("medicina_pro_id") REFERENCES "logistica"."medicina_pro" ("id"),
  ADD FOREIGN KEY ("sala_id") REFERENCES "logistica"."sala" ("sala_id"),
  ADD FOREIGN KEY ("usuario_enfermero_id") REFERENCES "usuarios"."usuario" ("usuario_id");

ALTER TABLE "logistica"."observacion_enfermeria"
  ADD FOREIGN KEY ("sala_id") REFERENCES "logistica"."sala" ("sala_id"),
  ADD FOREIGN KEY ("paciente_id") REFERENCES "logistica"."paciente" ("paciente_id"),
  ADD FOREIGN KEY ("sesion_id") REFERENCES "logistica"."protocolo_sesion" ("sesion_id"),
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios"."usuario" ("usuario_id");

ALTER TABLE "logistica"."reaccion_adversa"
  ADD FOREIGN KEY ("paciente_id") REFERENCES "logistica"."paciente" ("paciente_id"),
  ADD FOREIGN KEY ("sesion_id") REFERENCES "logistica"."protocolo_sesion" ("sesion_id"),
  ADD FOREIGN KEY ("transfusion_id") REFERENCES "desechable"."transfusion" ("transfusion_id"),
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios"."usuario" ("usuario_id");

ALTER TABLE "usuarios"."usuario" ADD FOREIGN KEY ("persona_id") REFERENCES "persona" ("persona_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios"."usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "usuarios"."rol" ("rol_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios"."auditoria" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios"."usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."cita" ADD FOREIGN KEY ("consulta_id") REFERENCES "logistica"."consulta" ("consulta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."consulta" ADD FOREIGN KEY ("paciente_id") REFERENCES "logistica"."paciente" ("paciente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."consulta" ADD FOREIGN KEY ("medico_id") REFERENCES "usuarios"."usuario" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."consulta" ADD FOREIGN KEY ("enfermedad_id") REFERENCES "logistica"."enfermedad" ("enfermedad_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."medicina_pro" ADD FOREIGN KEY ("id_protocolo") REFERENCES "logistica"."protocolo" ("protocolo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."medicina_pro" ADD FOREIGN KEY ("id_medicina") REFERENCES "logistica"."medicina" ("medicina_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "logistica"."medicina_pro" ADD FOREIGN KEY ("id_fase") REFERENCES "logistica"."fase" ("fase_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("estado_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipio" ("municipio_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "persona" ADD FOREIGN KEY ("parroquia_id") REFERENCES "parroquia" ("parroquia_id") DEFERRABLE INITIALLY IMMEDIATE;
